"""empty message

Revision ID: 21ef8b4d8504
Revises: 8bb046db9ae7
Create Date: 2017-12-05 16:51:26.046699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21ef8b4d8504'
down_revision = '8bb046db9ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('buildtime', sa.String(length=80), nullable=True))
    op.add_column('task', sa.Column('finishtime', sa.String(length=120), nullable=True))
    op.add_column('task', sa.Column('plantime', sa.String(length=120), nullable=True))
    op.add_column('task', sa.Column('project', sa.String(length=120), nullable=True))
    op.drop_column('task', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('task', 'project')
    op.drop_column('task', 'plantime')
    op.drop_column('task', 'finishtime')
    op.drop_column('task', 'buildtime')
    # ### end Alembic commands ###
