"""empty message

Revision ID: 65523db50b4b
Revises: 21ef8b4d8504
Create Date: 2017-12-05 20:35:53.186596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65523db50b4b'
down_revision = '21ef8b4d8504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user')
    # ### end Alembic commands ###
