"""empty message

Revision ID: 8bb046db9ae7
Revises: 
Create Date: 2017-12-02 16:10:08.655950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb046db9ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(length=80), nullable=True))
    op.drop_index('task', table_name='task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('task', 'task', ['task'], unique=True)
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
